import { supabase, isSupabaseConfigured } from './supabase';
export type SyncEventType = 'SYNC_ALL' | 'STORAGE_SYNC' | 'SYNC_ERROR' | 'ITEM_SCANNED' | 'ITEM_UPDATED' | 'ITEM_DELETED' | 'BATCH_CREATED' | 'BATCH_UPDATED' | 'BATCH_CLOSED' | 'GATE_ENTRY_CREATED' | 'GATE_ENTRY_UPDATED' | 'AUDIT_RECORD_ADDED' | 'DEVICE_HEARTBEAT' | 'DEVICE_LOGIN' | 'DEVICE_LOGOUT' | 'DEVICE_SESSION_UPDATED' | 'USER_UPDATED' | 'MASTERS_UPDATED';
export interface SyncMessage { type: SyncEventType; payload?: any; timestamp: string; senderId?: string; }
type SyncCallback = (msg: SyncMessage) => void;
class RealtimeSyncManager {
  private broadcastChannel: BroadcastChannel | null = null; private subscribers = new Set<SyncCallback>(); private supabaseChannel: any = null;
  private currentDeviceId = ''; private reconnectTimer: ReturnType<typeof setTimeout> | null = null; private heartbeatTimer: ReturnType<typeof setInterval> | null = null;
  private isOnline = typeof navigator === 'undefined' ? true : navigator.onLine; private reconnectDelay = 1000; private lastRealtimeStatus = 'DISCONNECTED';
  constructor() { this.currentDeviceId = this.getOrCreateDeviceId(); this.initBroadcastChannel(); this.initStorageEventListener(); this.initNetworkListeners(); this.initSupabaseRealtime(); this.startHeartbeat(); }
  public getDeviceId() { return this.currentDeviceId; }
  private getOrCreateDeviceId() { try { if (typeof window === 'undefined') return 'device-server'; let id = localStorage.getItem('emiza_device_unique_id'); if (!id) { id = `dev-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`; localStorage.setItem('emiza_device_unique_id', id); } return id; } catch { return `dev-${Date.now()}`; } }
  private initBroadcastChannel() { try { if (typeof window !== 'undefined' && 'BroadcastChannel' in window) { this.broadcastChannel = new BroadcastChannel('emiza_wop_realtime_sync'); this.broadcastChannel.onmessage = (e: MessageEvent<SyncMessage>) => { if (e.data && e.data.senderId !== this.currentDeviceId) this.notifySubscribers(e.data); }; } } catch (e) { console.warn('[SyncService] BroadcastChannel unavailable', e); } }
  private initStorageEventListener() { if (typeof window === 'undefined') return; window.addEventListener('storage', e => { if (e.key?.startsWith('emiza_')) this.notifySubscribers({ type: 'STORAGE_SYNC', payload: { key: e.key }, timestamp: new Date().toISOString(), senderId: 'storage-event' }); }); }
  private initNetworkListeners() { if (typeof window === 'undefined') return; window.addEventListener('online', () => { this.isOnline = true; this.reconnectDelay = 1000; this.initSupabaseRealtime(); this.notifySubscribers({ type: 'SYNC_ALL', payload: { reason: 'network_online' }, timestamp: new Date().toISOString(), senderId: this.currentDeviceId }); }); window.addEventListener('offline', () => { this.isOnline = false; this.notifySubscribers({ type: 'SYNC_ERROR', payload: { operation: 'realtime', message: 'Network connection is offline.' }, timestamp: new Date().toISOString(), senderId: this.currentDeviceId }); }); document.addEventListener('visibilitychange', () => { if (document.visibilityState === 'visible' && this.isOnline) { this.initSupabaseRealtime(); this.notifySubscribers({ type: 'SYNC_ALL', payload: { reason: 'visibility_change' }, timestamp: new Date().toISOString(), senderId: this.currentDeviceId }); } }); }
  private startHeartbeat() { if (typeof window === 'undefined') return; this.heartbeatTimer = setInterval(() => { if (this.isOnline && isSupabaseConfigured() && this.supabaseChannel) this.supabaseChannel.send({ type: 'broadcast', event: 'warehouse_heartbeat', payload: { deviceId: this.currentDeviceId, timestamp: new Date().toISOString() } }).catch?.(() => undefined); }, 15000); }
  public initSupabaseRealtime() {
    if (!isSupabaseConfigured() || !this.isOnline) return;
    try {
      if (this.supabaseChannel) { supabase.removeChannel(this.supabaseChannel).catch?.(() => undefined); this.supabaseChannel = null; }
      this.supabaseChannel = supabase.channel('emiza_warehouse_live_sync', { config: { broadcast: { self: false } } })
        .on('broadcast', { event: 'warehouse_update' }, ({ payload }) => { if (payload && payload.senderId !== this.currentDeviceId) this.notifySubscribers(payload); })
        .on('postgres_changes', { event: '*', schema: 'public', table: 'scanned_return_items' }, (p: any) => { const r = p.new || p.old; if (!r) return; const item = { id:r.id,batchId:r.batch_id||r.batchId,trackingNumber:r.tracking_number||r.trackingNumber,orderNumber:r.order_number||r.orderNumber,skuCode:r.sku_code||'',productName:r.product_name||'',remark:r.remark||'Good',photoUrl:r.photo_url,scannedAt:r.scanned_at||new Date().toISOString(),scannedBy:r.scanned_by||'',scannedByName:r.scanned_by_name||'Operator' }; this.notifySubscribers({ type:p.eventType==='DELETE'?'ITEM_DELETED':p.eventType==='UPDATE'?'ITEM_UPDATED':'ITEM_SCANNED', payload:{ item,itemId:r.id,batchId:r.batch_id||r.batchId }, timestamp:new Date().toISOString(), senderId:'supabase-postgres-changes' }); })
        .on('postgres_changes', { event: '*', schema: 'public', table: 'return_batches' }, (p: any) => { const r=p.new||p.old; if(!r)return; const batch={id:r.id,batchNumber:r.batch_number||r.batchNumber,batchType:r.batch_type||'RTO/B2C',warehouseId:r.warehouse_id,clientId:r.client_id,courierId:r.courier_id,status:r.status||'Open',dockNumber:r.dock_number,expectedCount:r.expected_count??0,totalScanned:r.total_scanned??0,remarksBreakdown:r.remarks_breakdown||{},createdAt:r.created_at,closedAt:r.closed_at,createdBy:r.created_by,createdByName:r.created_by_name,driverName:r.driver_name,driverMobile:r.driver_mobile,driverSignature:r.driver_signature,supervisorSigner:r.supervisor_signer,notes:r.notes}; this.notifySubscribers({type:p.eventType==='INSERT'?'BATCH_CREATED':'BATCH_UPDATED',payload:{batch,batchId:r.id},timestamp:new Date().toISOString(),senderId:'supabase-postgres-changes'}); })
        .on('postgres_changes', { event: '*', schema: 'public', table: 'inward_gate_entries' }, (p: any) => { const r=p.new||p.old;if(!r)return;const entry={id:r.id,gatePassNumber:r.gate_pass_number,warehouseId:r.warehouse_id,companyId:r.company_id,clientId:r.client_id,courierId:r.courier_id,vehicleNumber:r.vehicle_number,vehicleTypeId:r.vehicle_type_id,driverName:r.driver_name,driverMobile:r.driver_mobile,invoiceChallanNumber:r.invoice_challan_number,invoiceValue:r.invoice_value??0,expectedBoxCount:r.expected_box_count??0,receivedBoxCount:r.received_box_count??0,dockNumber:r.dock_number,status:r.status||'Arrived',entryTime:r.entry_time,createdBy:r.created_by};this.notifySubscribers({type:p.eventType==='INSERT'?'GATE_ENTRY_CREATED':'GATE_ENTRY_UPDATED',payload:{entry,id:r.id},timestamp:new Date().toISOString(),senderId:'supabase-postgres-changes'}); })
        .on('postgres_changes', { event: '*', schema: 'public', table: 'active_devices' }, (p:any) => this.notifySubscribers({type:'DEVICE_HEARTBEAT',payload:p.new||p.old,timestamp:new Date().toISOString(),senderId:'supabase-postgres-changes'}))
        .subscribe((status: string) => { this.lastRealtimeStatus=status; if(status==='SUBSCRIBED'){this.reconnectDelay=1000;console.info('[SyncService] Realtime connected');} else if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status)){this.notifySubscribers({type:'SYNC_ERROR',payload:{operation:'realtime',message:`Realtime ${status.toLowerCase()}; reconnecting.`},timestamp:new Date().toISOString(),senderId:this.currentDeviceId});this.scheduleReconnect();} });
    } catch (e:any) { console.error('[SyncService] Realtime init failed',e); this.notifySubscribers({type:'SYNC_ERROR',payload:{operation:'realtime',message:e?.message||'Realtime initialization failed'},timestamp:new Date().toISOString(),senderId:this.currentDeviceId}); this.scheduleReconnect(); }
  }
  private scheduleReconnect(){ if(!this.isOnline||!isSupabaseConfigured()||this.reconnectTimer)return; const delay=this.reconnectDelay; this.reconnectDelay=Math.min(this.reconnectDelay*2,30000); this.reconnectTimer=setTimeout(()=>{this.reconnectTimer=null;this.initSupabaseRealtime();},delay); }
  public broadcast(type: SyncEventType,payload?:any){const msg:SyncMessage={type,payload,timestamp:new Date().toISOString(),senderId:this.currentDeviceId};try{this.broadcastChannel?.postMessage(msg);}catch(e){console.warn('[SyncService] BroadcastChannel error',e);}if(isSupabaseConfigured()&&this.supabaseChannel)this.supabaseChannel.send({type:'broadcast',event:'warehouse_update',payload:msg}).catch?.((e:any)=>console.warn('[SyncService] Supabase broadcast error',e));this.notifySubscribers(msg);}
  public getStatus(){return this.lastRealtimeStatus;}
  public subscribe(cb:SyncCallback){this.subscribers.add(cb);return()=>this.subscribers.delete(cb);}
  private notifySubscribers(msg:SyncMessage){this.subscribers.forEach(cb=>{try{cb(msg);}catch(e){console.error('[SyncService] Subscriber error',e);}});}
}
export const SyncService = new RealtimeSyncManager();
