import {
  User,
  Company,
  Warehouse,
  Client,
  Courier,
  SKU,
  Driver,
  VehicleType,
  ReturnReason,
  InwardGateEntry,
  ReturnBatch,
  ScannedReturnItem,
  ActivityLog,
  AuditorDevice,
  AuditRecord,
  SupabaseConfig,
} from './types';

export const initialCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'EMIZA Supply Chain Services Pvt Ltd',
    code: 'EMIZA-HQ',
    gstin: '27AAAAA0000A1Z5',
    address: 'Bhiwandi Logistics Hub, Building 4, Thane, Maharashtra 421302',
    status: 'Active',
  },
];

export const initialWarehouses: Warehouse[] = [
  {
    id: 'wh-main',
    companyId: 'comp-1',
    code: 'WH-MAIN-01',
    name: 'EMIZA Central Fulfillment Facility',
    city: 'Bhiwandi / Mumbai Hub',
    address: 'Bldg A3, Indospace Park, National Highway 3, Bhiwandi, MH 421302',
    totalDocks: 16,
    contactPerson: 'Brijesh Verma',
    phone: '+91 98201 12345',
    status: 'Active',
  },
];

export const initialClients: Client[] = [
  {
    id: 'cli-bellavita',
    companyId: 'comp-1',
    code: 'CLI-BV',
    name: 'Bella Vita Organic & Luxury',
    email: 'ops@bellavitaorganic.com',
    phone: '+91 93117 32425',
    category: 'Fragrance & Cosmetics',
    status: 'Active',
  },
  {
    id: 'cli-nykaa',
    companyId: 'comp-1',
    code: 'CLI-NYK',
    name: 'Nykaa E-Retail Limited',
    email: 'logistics@nykaa.com',
    phone: '+91 22 6614 1000',
    category: 'Beauty & Fashion',
    status: 'Active',
  },
  {
    id: 'cli-mama',
    companyId: 'comp-1',
    code: 'CLI-MME',
    name: 'Honasa Consumer (Mamaearth)',
    email: 'warehouse.ops@mamaearth.in',
    phone: '+91 124 400 2300',
    category: 'Personal Care',
    status: 'Active',
  },
  {
    id: 'cli-boat',
    companyId: 'comp-1',
    code: 'CLI-BOAT',
    name: 'Imagine Marketing (boAt)',
    email: 'supplychain@boat-lifestyle.com',
    phone: '+91 22 4970 0000',
    category: 'Consumer Electronics',
    status: 'Active',
  },
  {
    id: 'cli-sugar',
    companyId: 'comp-1',
    code: 'CLI-SUG',
    name: 'Vellvette Lifestyle (SUGAR)',
    email: 'ops@sugarcosmetics.com',
    phone: '+91 22 2800 1122',
    category: 'Cosmetics',
    status: 'Active',
  },
];

export const initialCouriers: Courier[] = [
  {
    id: 'cour-delhivery',
    code: 'DELHIVERY',
    name: 'Delhivery Surface & Express',
    trackingFormatPattern: '14 DIGITS / DELH...',
    contactNumber: '1800-103-6354',
    apiSupported: true,
    status: 'Active',
  },
  {
    id: 'cour-bluedart',
    code: 'BLUEDART',
    name: 'Blue Dart Express Ltd',
    trackingFormatPattern: '11 DIGITS (e.g. 78201923841)',
    contactNumber: '1860-233-1234',
    apiSupported: true,
    status: 'Active',
  },
  {
    id: 'cour-xpressbees',
    code: 'XPRESSBEES',
    name: 'XpressBees Logistics',
    trackingFormatPattern: 'XB+12 DIGITS',
    contactNumber: '020-4911-6100',
    apiSupported: true,
    status: 'Active',
  },
  {
    id: 'cour-shadowfax',
    code: 'SHADOWFAX',
    name: 'Shadowfax Technologies',
    trackingFormatPattern: 'SFX+10 DIGITS',
    contactNumber: '080-6818-8000',
    apiSupported: true,
    status: 'Active',
  },
  {
    id: 'cour-ecom',
    code: 'ECOM_EXP',
    name: 'Ecom Express Ltd',
    trackingFormatPattern: 'ECOM+9 DIGITS',
    contactNumber: '0120-6868200',
    apiSupported: true,
    status: 'Active',
  },
];

export const initialSKUs: SKU[] = [
  {
    id: 'sku-bv-1',
    clientId: 'cli-bellavita',
    skuCode: 'BV-WHITE-OUD-100',
    eanBarcode: '8906105610014',
    name: 'Bella Vita Luxury White Oud Perfume 100ml',
    category: 'Perfume',
    unitPrice: 899,
    weightGrams: 350,
    status: 'Active',
  },
  {
    id: 'sku-bv-2',
    clientId: 'cli-bellavita',
    skuCode: 'BV-SKAI-AQUATIC-100',
    eanBarcode: '8906105610021',
    name: 'Bella Vita Skai Aquatic Eau De Cologne 100ml',
    category: 'Perfume',
    unitPrice: 799,
    weightGrams: 350,
    status: 'Active',
  },
  {
    id: 'sku-bv-3',
    clientId: 'cli-bellavita',
    skuCode: 'BV-CEO-MAN-100',
    eanBarcode: '8906105610038',
    name: 'Bella Vita CEO Man Luxury Perfume 100ml',
    category: 'Perfume',
    unitPrice: 899,
    weightGrams: 350,
    status: 'Active',
  },
  {
    id: 'sku-bv-4',
    clientId: 'cli-bellavita',
    skuCode: 'BV-EYELIFT-20G',
    eanBarcode: '8906105610052',
    name: 'Bella Vita Organic EyeLift Under Eye Cream Gel 20g',
    category: 'Skin Care',
    unitPrice: 349,
    weightGrams: 45,
    status: 'Active',
  },
  {
    id: 'sku-1',
    clientId: 'cli-nykaa',
    skuCode: 'NYK-LIP-RED-01',
    eanBarcode: '8901020304011',
    name: 'Matte Liquid Lipstick - Ruby Red 5ml',
    category: 'Makeup',
    unitPrice: 499,
    weightGrams: 45,
    status: 'Active',
  },
  {
    id: 'sku-2',
    clientId: 'cli-mama',
    skuCode: 'MME-ONION-SHAM-250',
    eanBarcode: '8904030506022',
    name: 'Onion Hair Fall Control Shampoo 250ml',
    category: 'Hair Care',
    unitPrice: 349,
    weightGrams: 290,
    status: 'Active',
  },
  {
    id: 'sku-3',
    clientId: 'cli-boat',
    skuCode: 'BOAT-Airdopes-141-BLK',
    eanBarcode: '8906040708033',
    name: 'Airdopes 141 TWS Earbuds - Bold Black',
    category: 'Audio',
    unitPrice: 1299,
    weightGrams: 150,
    status: 'Active',
  },
  {
    id: 'sku-4',
    clientId: 'cli-sugar',
    skuCode: 'SUG-FOUND-WARM-02',
    eanBarcode: '8908050901044',
    name: 'Ace Of Face Foundation Stick - Warm Sand',
    category: 'Cosmetics',
    unitPrice: 999,
    weightGrams: 80,
    status: 'Active',
  },
];

export const initialDrivers: Driver[] = [
  {
    id: 'drv-1',
    name: 'Suresh Kumar Yadav',
    mobile: '+91 98765 43210',
    licenseNumber: 'MH04 20180012345',
    transporterName: 'Om Logistics Transporters',
    status: 'Active',
  },
  {
    id: 'drv-2',
    name: 'Sunil Sharma',
    mobile: '+91 97654 32109',
    licenseNumber: 'DL01 20200054321',
    transporterName: 'Bella Vita Direct Fleet',
    status: 'Active',
  },
];

export const initialVehicleTypes: VehicleType[] = [
  { id: 'vt-1', typeName: '32ft Multi-Axle Container', capacityTons: 15, status: 'Active' },
  { id: 'vt-2', typeName: '24ft Container', capacityTons: 9, status: 'Active' },
  { id: 'vt-3', typeName: '14ft Eicher Truck', capacityTons: 4, status: 'Active' },
  { id: 'vt-4', typeName: 'Tata Ace / Bolero Pickup', capacityTons: 1.5, status: 'Active' },
];

export const initialReturnReasons: ReturnReason[] = [
  { id: 'rr-1', code: 'GOOD', label: 'Good', category: 'Both', requirePhoto: false, status: 'Active' },
  { id: 'rr-2', code: 'DAMAGE', label: 'Damage', category: 'Both', requirePhoto: true, status: 'Active' },
  { id: 'rr-3', code: 'OPEN_BOX', label: 'Open Box', category: 'RTO', requirePhoto: true, status: 'Active' },
  { id: 'rr-4', code: 'WRONG_PROD', label: 'Wrong Product', category: 'Both', requirePhoto: true, status: 'Active' },
  { id: 'rr-5', code: 'SHORT_QTY', label: 'Short Qty', category: 'Both', requirePhoto: false, status: 'Active' },
  { id: 'rr-6', code: 'MISSING_PROD', label: 'Missing Product', category: 'Both', requirePhoto: true, status: 'Active' },
  { id: 'rr-7', code: 'OTHERS', label: 'Others', category: 'Both', requirePhoto: false, status: 'Active' },
];

export const initialUsers: User[] = [
  {
    id: 'usr-super',
    name: 'Brijesh Verma (Super Admin)',
    email: 'verma.brijesh0501@gmail.com',
    role: 'Super Admin',
    assignedWarehouseIds: ['wh-main'],
    assignedClientIds: ['cli-bellavita', 'cli-nykaa', 'cli-mama', 'cli-boat', 'cli-sugar'],
    status: 'Active',
    lastLoginAt: '2026-08-22T08:30:00Z',
  },
  {
    id: 'usr-wh-mgr',
    name: 'Vikram Mehta (WH Manager)',
    email: 'vikram.m@emiza.com',
    role: 'Warehouse Manager',
    assignedWarehouseIds: ['wh-main'],
    assignedClientIds: ['cli-bellavita', 'cli-nykaa', 'cli-boat'],
    status: 'Active',
    lastLoginAt: '2026-08-22T07:15:00Z',
  },
  {
    id: 'usr-sup',
    name: 'Pooja Deshmukh (Supervisor)',
    email: 'pooja.d@emiza.com',
    role: 'Supervisor',
    assignedWarehouseIds: ['wh-main'],
    assignedClientIds: ['cli-bellavita', 'cli-nykaa', 'cli-mama', 'cli-boat', 'cli-sugar'],
    status: 'Active',
    lastLoginAt: '2026-08-22T08:00:00Z',
  },
  {
    id: 'usr-op1',
    name: 'Amit Patel (Scanner Operator)',
    email: 'amit.p@emiza.com',
    role: 'Operator',
    assignedWarehouseIds: ['wh-main'],
    assignedClientIds: ['cli-bellavita', 'cli-nykaa'],
    status: 'Active',
    lastLoginAt: '2026-08-22T08:12:00Z',
  },
];

// 15 Auditor Devices for multi-device cycle counting
export const initialAuditorDevices: AuditorDevice[] = [
  { id: 'AUD-01', name: 'Scanner 01 - Bay A (Perfume High Rack)', assignedPerson: 'Ravi Kumar', zone: 'Zone A - Fragrance', status: 'Active', batteryPercent: 94, lastActiveAt: 'Just now' },
  { id: 'AUD-02', name: 'Scanner 02 - Bay B (Skin & Cosmetics)', assignedPerson: 'Suresh Patil', zone: 'Zone B - Skincare', status: 'Active', batteryPercent: 88, lastActiveAt: '2 min ago' },
  { id: 'AUD-03', name: 'Scanner 03 - Mezzanine Rack 01', assignedPerson: 'Ajay Sharma', zone: 'Mezzanine Level 1', status: 'Active', batteryPercent: 91, lastActiveAt: 'Just now' },
  { id: 'AUD-04', name: 'Scanner 04 - Mezzanine Rack 02', assignedPerson: 'Manoj Verma', zone: 'Mezzanine Level 2', status: 'Active', batteryPercent: 76, lastActiveAt: '5 min ago' },
  { id: 'AUD-05', name: 'Scanner 05 - Pallet Inward Area', assignedPerson: 'Sunil Gupta', zone: 'Dock / Inward Stage', status: 'Active', batteryPercent: 82, lastActiveAt: '1 min ago' },
  { id: 'AUD-06', name: 'Scanner 06 - Bulk Storage Floor', assignedPerson: 'Deepak Sawant', zone: 'Bulk Floor - West', status: 'Active', batteryPercent: 65, lastActiveAt: '12 min ago' },
  { id: 'AUD-07', name: 'Scanner 07 - Fast Moving Aisle 1', assignedPerson: 'Karan Joshi', zone: 'Fast Pick Aisle 1', status: 'Idle', batteryPercent: 98, lastActiveAt: '30 min ago' },
  { id: 'AUD-08', name: 'Scanner 08 - Fast Moving Aisle 2', assignedPerson: 'Vikas Shinde', zone: 'Fast Pick Aisle 2', status: 'Active', batteryPercent: 70, lastActiveAt: '4 min ago' },
  { id: 'AUD-09', name: 'Scanner 09 - Returns Quarantine', assignedPerson: 'Pankaj Rathod', zone: 'QC & Quarantine', status: 'Active', batteryPercent: 85, lastActiveAt: 'Just now' },
  { id: 'AUD-10', name: 'Scanner 10 - High Value Cage', assignedPerson: 'Naresh Jain', zone: 'Secure Vault Cage', status: 'Active', batteryPercent: 95, lastActiveAt: '7 min ago' },
  { id: 'AUD-11', name: 'Scanner 11 - Packing Buffer A', assignedPerson: 'Anil Yadav', zone: 'Pack Station Line 1', status: 'Idle', batteryPercent: 60, lastActiveAt: '1 hr ago' },
  { id: 'AUD-12', name: 'Scanner 12 - Packing Buffer B', assignedPerson: 'Vijay Chauhan', zone: 'Pack Station Line 2', status: 'Idle', batteryPercent: 55, lastActiveAt: '45 min ago' },
  { id: 'AUD-13', name: 'Scanner 13 - Dispatch Dock 01', assignedPerson: 'Rohit Mali', zone: 'Outward Bay 1', status: 'Active', batteryPercent: 78, lastActiveAt: '10 min ago' },
  { id: 'AUD-14', name: 'Scanner 14 - Dispatch Dock 02', assignedPerson: 'Sachin Waghmare', zone: 'Outward Bay 2', status: 'Active', batteryPercent: 84, lastActiveAt: '15 min ago' },
  { id: 'AUD-15', name: 'Scanner 15 - Supervisor Master Gun', assignedPerson: 'Brijesh Verma', zone: 'Central Control Hub', status: 'Active', batteryPercent: 100, lastActiveAt: 'Just now' },
];

// Inward Gate entries - Bella Vita has 2 Vehicles and 100 Boxes total!
export const initialInwardGateEntries: InwardGateEntry[] = [
  {
    id: 'gate-bv-01',
    gatePassNumber: 'GP-20260822-001',
    warehouseId: 'wh-main',
    companyId: 'comp-1',
    clientId: 'cli-bellavita',
    courierId: 'cour-delhivery',
    vehicleNumber: 'MH04 BV 1001',
    vehicleTypeId: 'vt-3',
    driverName: 'Suresh Kumar Yadav',
    driverMobile: '+91 98765 43210',
    driverLicense: 'MH04 20180012345',
    invoiceChallanNumber: 'CH-BV-9821-A',
    invoiceValue: 540000,
    expectedBoxCount: 60,
    receivedBoxCount: 60,
    dockNumber: 'Dock 01',
    status: 'Unloading',
    entryTime: '2026-08-22T07:30:00Z',
    dockAllocatedTime: '2026-08-22T07:45:00Z',
    createdBy: 'usr-op1',
    remarks: 'Bella Vita Fragrance Batch - 60 Boxes received intact.',
  },
  {
    id: 'gate-bv-02',
    gatePassNumber: 'GP-20260822-002',
    warehouseId: 'wh-main',
    companyId: 'comp-1',
    clientId: 'cli-bellavita',
    courierId: 'cour-bluedart',
    vehicleNumber: 'MH04 BV 2002',
    vehicleTypeId: 'vt-4',
    driverName: 'Sunil Sharma',
    driverMobile: '+91 97654 32109',
    driverLicense: 'DL01 20200054321',
    invoiceChallanNumber: 'CH-BV-9822-B',
    invoiceValue: 360000,
    expectedBoxCount: 40,
    receivedBoxCount: 40,
    dockNumber: 'Dock 03',
    status: 'Dock Allocated',
    entryTime: '2026-08-22T08:15:00Z',
    dockAllocatedTime: '2026-08-22T08:25:00Z',
    createdBy: 'usr-op1',
    remarks: 'Bella Vita Skincare Batch - 40 Boxes ready for verification.',
  },
  {
    id: 'gate-1001',
    gatePassNumber: 'GP-20260822-003',
    warehouseId: 'wh-main',
    companyId: 'comp-1',
    clientId: 'cli-nykaa',
    courierId: 'cour-delhivery',
    vehicleNumber: 'MH04 JK 8821',
    vehicleTypeId: 'vt-1',
    driverName: 'Ramesh Singh',
    driverMobile: '+91 98111 22334',
    driverLicense: 'MH04 20190088211',
    invoiceChallanNumber: 'INV-NYK-89211',
    invoiceValue: 450000,
    expectedBoxCount: 120,
    receivedBoxCount: 120,
    dockNumber: 'Dock 04',
    status: 'Unloading',
    entryTime: '2026-08-22T07:40:00Z',
    dockAllocatedTime: '2026-08-22T07:55:00Z',
    createdBy: 'usr-op1',
    remarks: 'Cosmetics consignment 120 boxes.',
  },
  {
    id: 'gate-1002',
    gatePassNumber: 'GP-20260822-004',
    warehouseId: 'wh-main',
    companyId: 'comp-1',
    clientId: 'cli-boat',
    courierId: 'cour-bluedart',
    vehicleNumber: 'DL01 GA 4321',
    vehicleTypeId: 'vt-3',
    driverName: 'Rajesh Vishwakarma',
    driverMobile: '+91 97654 32109',
    driverLicense: 'DL01 20200054321',
    invoiceChallanNumber: 'CH-BOAT-4412',
    invoiceValue: 890000,
    expectedBoxCount: 85,
    receivedBoxCount: 85,
    dockNumber: 'Dock 02',
    status: 'Completed',
    entryTime: '2026-08-22T06:30:00Z',
    dockAllocatedTime: '2026-08-22T06:45:00Z',
    createdBy: 'usr-op1',
    remarks: 'Electronics shipment verified and putaway completed.',
  },
];

// Return batches with exact Account-wise breakdown including Bella Vita - 100 Total (90 Good, 10 Bad/Others)
export const initialReturnBatches: ReturnBatch[] = [
  {
    id: 'batch-bv-100',
    batchNumber: 'RTO-BV-20260822-01',
    batchType: 'RTO/B2C',
    warehouseId: 'wh-main',
    clientId: 'cli-bellavita',
    courierId: 'cour-delhivery',
    status: 'Open',
    expectedCount: 100,
    totalScanned: 100,
    remarksBreakdown: {
      'Good': 90,
      'Damage': 5,
      'Open Box': 2,
      'Wrong Product': 1,
      'Short Qty': 1,
      'Missing Product': 1,
      'Others': 0,
    },
    createdAt: '2026-08-22T08:00:00Z',
    createdBy: 'usr-op1',
    createdByName: 'Amit Patel',
    notes: 'Bella Vita Return Consignment: 100 Units audited (90 Good, 10 Bad/Defect).',
  },
  {
    id: 'batch-2001',
    batchNumber: 'RTO-NYK-20260822-02',
    batchType: 'RTO/B2C',
    warehouseId: 'wh-main',
    clientId: 'cli-nykaa',
    courierId: 'cour-delhivery',
    status: 'Open',
    expectedCount: 80,
    totalScanned: 65,
    remarksBreakdown: {
      'Good': 52,
      'Damage': 6,
      'Open Box': 4,
      'Wrong Product': 2,
      'Short Qty': 1,
      'Missing Product': 0,
      'Others': 0,
    },
    createdAt: '2026-08-22T08:15:00Z',
    createdBy: 'usr-op1',
    createdByName: 'Amit Patel',
    notes: 'Nykaa morning RTO returns scan.',
  },
  {
    id: 'batch-2002',
    batchNumber: 'B2B-BOAT-20260821-01',
    batchType: 'B2B Return',
    warehouseId: 'wh-main',
    clientId: 'cli-boat',
    courierId: 'cour-bluedart',
    status: 'Closed',
    expectedCount: 50,
    totalScanned: 50,
    remarksBreakdown: {
      'Good': 42,
      'Damage': 4,
      'Open Box': 2,
      'Wrong Product': 1,
      'Short Qty': 0,
      'Missing Product': 1,
      'Others': 0,
    },
    createdAt: '2026-08-21T14:20:00Z',
    closedAt: '2026-08-21T16:45:00Z',
    createdBy: 'usr-sup',
    createdByName: 'Pooja Deshmukh',
    driverName: 'Rajesh Vishwakarma',
    driverMobile: '+91 97654 32109',
    driverSignature: 'SIGNED',
    supervisorSigner: 'Pooja Deshmukh',
    notes: 'boAt B2B Distributor returns reconciled and closed.',
  },
  {
    id: 'batch-2003',
    batchNumber: 'RTO-MME-20260822-01',
    batchType: 'RTO/B2C',
    warehouseId: 'wh-main',
    clientId: 'cli-mama',
    courierId: 'cour-xpressbees',
    status: 'Open',
    expectedCount: 40,
    totalScanned: 35,
    remarksBreakdown: {
      'Good': 28,
      'Damage': 4,
      'Open Box': 1,
      'Wrong Product': 1,
      'Short Qty': 1,
      'Missing Product': 0,
      'Others': 0,
    },
    createdAt: '2026-08-22T08:45:00Z',
    createdBy: 'usr-op1',
    createdByName: 'Amit Patel',
    notes: 'Mamaearth Onion series customer returns.',
  },
];

export const initialScannedItems: ScannedReturnItem[] = [
  {
    id: 'item-bv-01',
    batchId: 'batch-bv-100',
    trackingNumber: 'DEL-BV-8890101',
    orderNumber: 'ORD-BV-901',
    skuCode: 'BV-WHITE-OUD-100',
    productName: 'Bella Vita Luxury White Oud Perfume 100ml',
    remark: 'Good',
    scannedAt: '2026-08-22T08:05:12Z',
    scannedBy: 'usr-op1',
    scannedByName: 'Amit Patel',
  },
  {
    id: 'item-bv-02',
    batchId: 'batch-bv-100',
    trackingNumber: 'DEL-BV-8890102',
    orderNumber: 'ORD-BV-902',
    skuCode: 'BV-SKAI-AQUATIC-100',
    productName: 'Bella Vita Skai Aquatic Eau De Cologne 100ml',
    remark: 'Damage',
    photoUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=300',
    scannedAt: '2026-08-22T08:07:44Z',
    scannedBy: 'usr-op1',
    scannedByName: 'Amit Patel',
  },
];

// Initial Audit (Cycle Count) records across multiple auditor guns
export const initialAuditRecords: AuditRecord[] = [
  {
    id: 'aud-rec-1',
    auditorDeviceId: 'AUD-01',
    auditorName: 'Ravi Kumar',
    clientId: 'cli-bellavita',
    clientName: 'Bella Vita Organic & Luxury',
    mode: 'WITH_BATCH',
    skuCode: 'BV-WHITE-OUD-100',
    eanBarcode: '8906105610014',
    productName: 'Bella Vita Luxury White Oud Perfume 100ml',
    location: 'A-01-02-B',
    quantity: 48,
    batchNumber: 'BV-BAT-2026-A1',
    mfgDate: '2026-01-15',
    expDate: '2028-01-14',
    qcStatus: 'Good',
    scannedAt: '2026-08-22T08:15:30Z',
    notes: 'Master carton sealed and verified.',
  },
  {
    id: 'aud-rec-2',
    auditorDeviceId: 'AUD-01',
    auditorName: 'Ravi Kumar',
    clientId: 'cli-bellavita',
    clientName: 'Bella Vita Organic & Luxury',
    mode: 'WITH_BATCH',
    skuCode: 'BV-SKAI-AQUATIC-100',
    eanBarcode: '8906105610021',
    productName: 'Bella Vita Skai Aquatic Eau De Cologne 100ml',
    location: 'A-01-03-A',
    quantity: 60,
    batchNumber: 'BV-BAT-2026-A2',
    mfgDate: '2026-02-10',
    expDate: '2028-02-09',
    qcStatus: 'Good',
    scannedAt: '2026-08-22T08:22:10Z',
  },
  {
    id: 'aud-rec-3',
    auditorDeviceId: 'AUD-02',
    auditorName: 'Suresh Patil',
    clientId: 'cli-bellavita',
    clientName: 'Bella Vita Organic & Luxury',
    mode: 'WITHOUT_BATCH',
    skuCode: 'BV-EYELIFT-20G',
    eanBarcode: '8906105610052',
    productName: 'Bella Vita Organic EyeLift Under Eye Cream Gel 20g',
    location: 'B-04-01-C',
    quantity: 120,
    qcStatus: 'Good',
    scannedAt: '2026-08-22T08:30:45Z',
    notes: 'Quick cycle count on pick face.',
  },
  {
    id: 'aud-rec-4',
    auditorDeviceId: 'AUD-03',
    auditorName: 'Ajay Sharma',
    clientId: 'cli-nykaa',
    clientName: 'Nykaa E-Retail Limited',
    mode: 'WITHOUT_BATCH',
    skuCode: 'NYK-LIP-RED-01',
    eanBarcode: '8901020304011',
    productName: 'Matte Liquid Lipstick - Ruby Red 5ml',
    location: 'MEZZ-01-05',
    quantity: 85,
    qcStatus: 'Good',
    scannedAt: '2026-08-22T08:35:00Z',
  },
  {
    id: 'aud-rec-5',
    auditorDeviceId: 'AUD-05',
    auditorName: 'Sunil Gupta',
    clientId: 'cli-boat',
    clientName: 'Imagine Marketing (boAt)',
    mode: 'WITH_BATCH',
    skuCode: 'BOAT-Airdopes-141-BLK',
    eanBarcode: '8906040708033',
    productName: 'Airdopes 141 TWS Earbuds - Bold Black',
    location: 'DOCK-PALLET-02',
    quantity: 150,
    batchNumber: 'BOAT-2026-Q1',
    mfgDate: '2026-03-01',
    expDate: '2029-03-01',
    qcStatus: 'Good',
    scannedAt: '2026-08-22T08:42:20Z',
  },
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: 'act-1',
    timestamp: '2026-08-22T08:45:00Z',
    userId: 'usr-op1',
    userName: 'Amit Patel',
    userRole: 'Operator',
    action: 'Created Inward Gate Pass',
    module: 'Inward',
    details: 'Gate pass GP-20260822-002 registered for Bella Vita vehicle MH04 BV 2002 (40 boxes)',
  },
  {
    id: 'act-2',
    timestamp: '2026-08-22T08:30:00Z',
    userId: 'usr-op1',
    userName: 'Ravi Kumar',
    userRole: 'Operator',
    action: 'Audit Scan Saved',
    module: 'Audit',
    details: 'Auditor Gun AUD-01 scanned 48 units of Bella Vita White Oud at location A-01-02-B',
  },
  {
    id: 'act-3',
    timestamp: '2026-08-22T08:00:00Z',
    userId: 'usr-op1',
    userName: 'Amit Patel',
    userRole: 'Operator',
    action: 'Audited Bella Vita Returns',
    module: 'RTO',
    details: 'Bella Vita Batch RTO-BV-20260822-01: 100 scanned (90 Good, 10 Defect)',
  },
];

export const initialSupabaseConfig: SupabaseConfig = {
  supabaseUrl: 'https://xyzcompany.supabase.co',
  supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
  autoSyncEnabled: false,
  connectedStatus: 'Disconnected',
};

